service: my-lex-bot-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'test'}

functions:
  lexbot:
    handler: src/index.handler
    events:
      - http:
          path: lexbot
          method: post
          cors: true