service: github-copilot-lex-bot-test-v1

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  lex-bot:
    handler: handler.bot
    events:
      - http:
          path: bot
          method: post